# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  # Temporarily disabled custom_lint to resolve compilation issues
  # plugins:
  #   - custom_lint

linter:
  rules:
    # Additional lint rules
    prefer_single_quotes: true
    avoid_print: false  # Allow prints for development
